"""
Async auto-captioner. Calls OpenRouter (Gemini 3.1 Pro by default) on a pool of
audio files, writes captions to .txt sidecars next to each audio file, and
streams progress via a shared status object.

Concurrency is bounded by an asyncio.Semaphore. Stats per call are appended to
~/.config/sa3-inpainter/captioner_stats.json for cost-estimation.
"""

from __future__ import annotations
import asyncio, base64, io, json, os, time
from dataclasses import dataclass, field, asdict
from pathlib import Path

import numpy as np
import soundfile as sf
import aiohttp


DEFAULT_MODEL = "google/gemini-3.1-pro-preview"
DEFAULT_EXAMPLES = [
    "soundscape with piano arps, indie pop with male vocals, offbeat bassline with house drums and ambient electric guitar",
    "bright synth leads, pitched vocal chops, disco house, euphoric and danceable",
    "ethereal electric piano intro, fast 808 melody, experimental drill, plucked guitar outro",
]
TARGET_SR    = 16000
STATS_PATH   = Path.home() / ".config" / "sa3-inpainter" / "captioner_stats.json"

SYSTEM_PROMPT = (
    "You are captioning this audio for an audio generation model. Match the "
    "style used in the provided examples when writing your own caption — same "
    "format, length, and level of detail, but describe what you actually hear. "
    "Pay close attention to the full audio — it's easy to confuse genres or "
    "fixate on the intro; make sure what you write reflects what's actually "
    "going on across the whole clip."
)

def _user_prompt(examples: list[str]) -> str:
    lines = ["Caption format examples (one caption per line):", ""]
    for ex in examples: lines.append(f"- {ex}")
    lines += ["", "Now caption the attached audio in the same style. Output just the caption line."]
    return "\n".join(lines)


def _trim_and_encode(path: Path) -> tuple[str, int, int]:
    """Returns (base64 wav, raw_bytes, audio_seconds).

    Sends the full audio (no clipping) downsampled to TARGET_SR mono. Captioning
    a 4-minute track this way is ~10× more audio tokens than a 30s clip, but
    short clips routinely mislabel: a cinematic intro on a hardstyle song reads
    as "orchestral, soundscape" and poisons the trained genre association.
    """
    audio, sr = sf.read(str(path))
    if audio.ndim == 2: audio = audio.mean(axis=1)
    audio = audio.astype(np.float32)
    if sr != TARGET_SR:
        new_len = int(len(audio) * (TARGET_SR / sr))
        idx = np.linspace(0, len(audio) - 1, new_len)
        audio = np.interp(idx, np.arange(len(audio)), audio).astype(np.float32)
    buf = io.BytesIO()
    sf.write(buf, audio, TARGET_SR, subtype="PCM_16", format="WAV")
    raw = buf.getvalue()
    return base64.b64encode(raw).decode("ascii"), len(raw), int(len(audio) / TARGET_SR)


def _load_stats() -> dict:
    if STATS_PATH.exists():
        try:    return json.loads(STATS_PATH.read_text())
        except: pass
    return {"schema": 1, "note": "Auto-generated by captioner.", "calls": []}


def _save_stats(stats: dict):
    STATS_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATS_PATH.write_text(json.dumps(stats, indent=2))


def append_stat(call: dict):
    stats = _load_stats()
    stats["calls"].append(call)
    # cap to last 5000
    if len(stats["calls"]) > 5000:
        stats["calls"] = stats["calls"][-5000:]
    _save_stats(stats)


def estimate_cost(n_files: int, model: str = DEFAULT_MODEL) -> dict:
    """Use historical call stats for this model to predict cost."""
    stats = _load_stats()
    calls = [c for c in stats.get("calls", []) if c.get("model") == model]
    if not calls:
        return {"per_call": None, "total": None, "n_samples": 0}
    costs = [c.get("cost_usd", 0) for c in calls[-50:]]   # last 50 most recent
    avg = sum(costs) / len(costs)
    return {"per_call": avg, "total": avg * n_files, "n_samples": len(costs)}


# ── progress / status object ──────────────────────────────────────────────
@dataclass
class CaptionStatus:
    running: bool = False
    cancelled: bool = False
    total: int = 0
    done: int = 0
    failed: int = 0
    errors: list[str] = field(default_factory=list)
    started_ts: float = 0.0
    finished_ts: float = 0.0
    in_flight: list[str] = field(default_factory=list)   # filenames currently being captioned
    last_captioned: list[dict] = field(default_factory=list)  # [{file, caption}, ...] recent
    cost_so_far: float = 0.0
    parallel: int = 32
    model: str = DEFAULT_MODEL
    lora_name: str = ""
    folder: str = ""

    def snapshot(self) -> dict:
        d = asdict(self)
        return d


# Single shared status (one captioning job at a time per process)
status = CaptionStatus()


async def _caption_one(session: aiohttp.ClientSession, sem: asyncio.Semaphore,
                       api_key: str, audio_path: Path, folder: Path,
                       examples: list[str], model: str) -> dict:
    name = audio_path.name
    async with sem:
        if status.cancelled:
            return {"file": name, "skipped": True}
        status.in_flight.append(name)
        try:
            b64, raw_bytes, audio_seconds = _trim_and_encode(audio_path)
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": [
                        {"type": "text", "text": _user_prompt(examples)},
                        {"type": "input_audio", "input_audio": {"data": b64, "format": "wav"}},
                    ]},
                ],
                "temperature": 0.6,
                "usage": {"include": True},
            }
            headers = {"Authorization": f"Bearer {api_key}",
                       "Content-Type": "application/json"}
            t0 = time.time()
            async with session.post(
                "https://openrouter.ai/api/v1/chat/completions",
                json=payload, headers=headers,
                timeout=aiohttp.ClientTimeout(total=120),
            ) as resp:
                body = await resp.json()
                dt = time.time() - t0
            if resp.status != 200:
                err = (body or {}).get("error", {}).get("message", f"http {resp.status}")
                status.failed += 1
                status.errors.append(f"{name}: {err}")
                return {"file": name, "error": err}

            try:
                content = body["choices"][0]["message"]["content"].strip()
            except Exception:
                content = ""
            usage = body.get("usage", {}) or {}
            cost  = float(usage.get("cost", 0) or 0)

            # Write caption sidecar
            if content:
                txt_path = folder / (audio_path.stem + ".txt")
                try:
                    txt_path.write_text(content, encoding="utf-8")
                except Exception as e:
                    status.errors.append(f"{name}: write failed — {e}")
                    status.failed += 1
                    return {"file": name, "error": str(e)}

            # Stats
            try:
                append_stat({
                    "ts": int(time.time()),
                    "model": model,
                    "audio_seconds": audio_seconds,
                    "sample_rate": TARGET_SR,
                    "prompt_tokens": usage.get("prompt_tokens"),
                    "completion_tokens": usage.get("completion_tokens"),
                    "reasoning_tokens": (usage.get("completion_tokens_details") or {}).get("reasoning_tokens"),
                    "audio_tokens": (usage.get("prompt_tokens_details") or {}).get("audio_tokens"),
                    "duration_sec": round(dt, 2),
                    "cost_usd": cost,
                    "file": name,
                })
            except Exception: pass

            status.done += 1
            status.cost_so_far += cost
            status.last_captioned.append({"file": name, "caption": content, "cost": cost})
            if len(status.last_captioned) > 30:
                status.last_captioned = status.last_captioned[-30:]
            return {"file": name, "caption": content, "cost": cost, "duration": dt}
        except Exception as e:
            status.failed += 1
            status.errors.append(f"{name}: {e}")
            return {"file": name, "error": str(e)}
        finally:
            try: status.in_flight.remove(name)
            except ValueError: pass


async def run_caption_batch(api_key: str, folder: Path, files: list[Path],
                            examples: list[str], parallel: int, model: str,
                            lora_name: str = ""):
    status.running = True
    status.cancelled = False
    status.total = len(files)
    status.done = 0
    status.failed = 0
    status.errors = []
    status.started_ts = time.time()
    status.finished_ts = 0.0
    status.in_flight = []
    status.last_captioned = []
    status.cost_so_far = 0.0
    status.parallel = parallel
    status.model = model
    status.lora_name = lora_name
    status.folder = str(folder)

    sem = asyncio.Semaphore(max(1, min(256, parallel)))
    timeout = aiohttp.ClientTimeout(total=None, connect=30, sock_read=120)
    async with aiohttp.ClientSession(timeout=timeout) as sesh:
        tasks = [
            _caption_one(sesh, sem, api_key, p, folder, examples, model)
            for p in files
        ]
        await asyncio.gather(*tasks, return_exceptions=True)

    status.running = False
    status.finished_ts = time.time()
